Initial Version: kyverno `v1.4.2`
projectsyn/component-kyverno pull request #2
Opened 2021-08-23 13:13 UTC by bastjan

## Checklist

- [ ] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

2021-08-24 14:34 UTC, glrf requested changes

2021-08-24 14:34 UTC, glrf commented on class/defaults.yml
> +        version: ${kyverno:images:kyverno:version}
These are never actually set or am I missing something?

2021-08-24 14:54 UTC, bastjan commented on class/defaults.yml
> +        version: ${kyverno:images:kyverno:version}
They are never actually set 🤦‍♀️

2021-08-25 09:31 UTC, glrf approved these changes

2021-08-25 11:36 UTC, merged